### PR TITLE
fix content type issue defaulting to octet-stream

### LINKED ISSUE #114: Uploaded files have a bad Blob type, a bad Content Type and don't upload fully
**Describe your question**
When creating a post with images, the images do not upload fully.

Looking at them in the Microsoft Azure Storage Explorer, I note three oddities differing from what I see if I use the Storage Explorer to upload those same images.

1.  The Blob Type is Append Blob rather than Block Blob.
2.  The Content Type is text/plain rather than image/jpeg
3.  The file size is 0 rather than the correct size

Please note that I amusing version 4.1.0 of the plug-in since, as several users have noted, version 4.3 simply does not work at all.

Given that MASE uploads correctly, I'm not sure what to do.

Any help would be greatly appreciated.

TIA.

### LINKED ISSUE #210: Incorrect Content-Type being applied to uploaded files in v 4.4.0
### Describe the bug

When uploading files via the WP admin, the Content Type is being incorrectly applied in Azure. All files, regardless of file type, are being uploaded to Azure with the content type of `application/octet-stream`. 

In WordPress, the attachment details show the correct content type.

This is causing PDFs to automatically download vs open in the browser. This is the case for all uploaded media files as well.

Changing the content type via the Azure interface resolves the behavior issue, but manually resolving for every file uploaded to a multiuser multisite is not a reasonable workflow. 

Downgrading to v 4.3.5 fixes the issue and the correct content type is applied.

### Steps to Reproduce

1. Upload a file of any kind via WP admin
2. In the attachment details, copy the file url and paste in browser. File will download instead of being viewed in the browser.
3. To test file type, `curl -v` the file url and see that content type is: `Content-Type: application/octet-stream`

### Screenshots, screen recording, code snippet

_No response_

### Environment information

_No response_

### WordPress information

Microsoft Azure Storage for WordPress v4.4.0
WordPress v6.3.1, this is a multisite
php v8.2
mysql v8

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by hugosolar**
### Description of the Change
This PR ensures that the blob is being sent to the storage with the proper content type as we're experiencing issues with some containers defaulting the content type to `application/octet-stream`
With this fix, we're not leaving the default content type but sending the file content type directly to the `createBlockBlob()` function through the `$options` parameters

Fixes #210

### How to test the Change
- Using the plugin, upload an image to the blob container
- Using Azure storage explores, verify the proper content type is being set in the blob container

### Credits
@hugosolar 

### Checklist:
- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

### CODE REVIEW

File: includes/class-windows-azure-rest-api-client.php [hunk 1]
```diff
@@ -985,10 +986,11 @@ public function put_blobs( $container, array $files = array() ) {
 	 * @param string $local_path               Local path.
 	 * @param string $remote_path              Remote path.
 	 * @param bool   $force_direct_file_access Whether to force direct file access.
+	 * @param string $content_type             File content type
 	 *
 	 * @return bool|string|WP_Error Newly put blob URI or WP_Error|false on failure.
 	 */
-	public function put_blob( $container, $local_path, $remote_path, $force_direct_file_access = false ) {
+	public function put_blob( $container, $local_path, $remote_path, $force_direct_file_access = false, $content_type = 'application/octet-stream' ) {
```
Comment (rickalee) [inline includes/class-windows-azure-rest-api-client.php:993]: @hugosolar At what point are we overriding the default of octet-stream with jpeg for instance?

Comment (hugosolar) [reply includes/class-windows-azure-rest-api-client.php:993]: @rickalee here we're sending the mime type
https://github.com/10up/windows-azure-storage/blob/2a9e451eb259e40d3c6fa6e7205a2c60af2ade12/includes/class-windows-azure-helper.php#L483
and here
https://github.com/10up/windows-azure-storage/blob/2a9e451eb259e40d3c6fa6e7205a2c60af2ade12/includes/class-windows-azure-helper.php#L417

**Review by rickalee — APPROVED** [review]
