### PR TITLE
fix path issue with override container

### LINKED ISSUE #243: Custom CNAME container name dublication in URL
### Describe the bug

After updating the plugin, all pictures became unavailable on the site.

For some reason, it duplicated the storage container in the photo URL: 

https://cdn.besdima.dev/besdimadev/besdimadev/2021/09/Photo2.jpg

Where it should be https://cdn.besdima.dev/besdimadev/2021/09/Photo2.jpg

### Steps to Reproduce

Happened after the automatic plugin update.

To reproduce, you need to have CNAME set in settings.
Create a new post.
Upload a picture.
After publication, the picture is not available due to the wrong URL.

### Screenshots, screen recording, code snippet

_No response_

### Environment information

OS: Linux
Server: nginx/1.26.1
Document Root: /home/site/wwwroot
PHP - v8.3.8

### WordPress information

Current version: 6.5.5

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
```[tasklist]
### Tasks
```

### LINKED ISSUE #244: Duplicating container directory in image address URL
### Describe the bug

I updated Microsoft Azure Storage for Wordpress to 4.5.0 in the Plugins window. After that I noticed several (random) images were broken. When I copied image address, I noticed duplication in the container name in URL. Example: https://cdn.coastalscience.noaa.gov/csmedia/csmedia/image.jpg
Currently, my only feasible fix is to rollback your plugin to version 4.4.2. Please fix, thank you!

### Steps to Reproduce

1. Open Wordpress Plugins screen
2. Notification to update Microsoft Azure Storage for Wordpress to 4.5.0, and click Update
3. Inspect website and see broken image icons. They are random. Many were on the homepage of one site, but other sites, had to look on subpages.
4. To resolve, rollback the version of Microsoft Azure Storage for Wordpress to 4.4.2

### Screenshots, screen recording, code snippet

_No response_

### Environment information

Browser Chrome and Edge

### WordPress information

Wordpress Version 6.5.5

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by hugosolar**
### Description of the Change

Fix path issue due to some override container checks. 

Closes #244 

### How to test the Change
Where possible, please also include:
- In the settings enable CNAME
- create a dummy post and add an image
- Save & publish the post
- In the frontend verify srcset paths are correct
- Verify container name is correct
- Set an override container name
- Go back to the dummy post
- add an image
- in the frontend verify srcset paths and container names are correct

### Changelog Entry

> Fixed - Fix path issue that shows the container name duplicated in URL paths

### Credits
Props @hugosolar, @cally423, @Besdima, @ms2oo8, @BCornelissen

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

### CODE REVIEW

File: windows-azure-storage-util.php [hunk 1]
```diff
@@ -315,7 +315,7 @@ protected static function _maybe_rewrite_cname( $cname ) {
 	public static function get_storage_url_base( $append_container = true ) {
 		$azure_storage_account_name                   = \Windows_Azure_Helper::get_account_name();
 		$default_azure_storage_account_container_name = \Windows_Azure_Helper::get_default_container();
-                $azure_storage_override_container_path        = \Windows_Azure_Helper::get_azure_storage_override_container_path();
+        $azure_storage_override_container_path        = \Windows_Azure_Helper::get_azure_storage_override_container_path();
```
Comment (dkotter) [inline windows-azure-storage-util.php]: Seems some spacing issues here, maybe using spaces instead of tabs?

**Review by dkotter — CHANGES_REQUESTED** [review]
Minor comment but otherwise code looks good.

Does this also close #243?

**Review by dkotter — APPROVED** [review]
